server:
  port: 8081

spring:
  application:
    name: CatalogApplication
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingstore
    username: admin
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mysql:
    url: jdbc:mysql://localhost:3306/shoppingstore
    username: admin
    password: root