server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Customer-Services
          uri: lb://Customer-Services
          predicates:
            - Path=/customer/**
          filters:
            - AuthFilter

        - id: Cart-Services
          uri: lb://Cart-Services
          predicates:
            - Path=/cart/**

        - id: Catalog-Services
          uri: lb://Catalog-Services
          predicates:
            - Path=/product/**

        - id: Auth-Services
          uri: lb://Auth-Services
          predicates:
            - Path=/auth/**
         
        - id: Payment-Services
          uri: lb://Payment-Services
          predicates:
            - Path=/pay/**
