server:
  port: 8081
Spring:
  cloud:
    config:
      server:
        git:
          default-label: ApiGateway
          uri: https://github.com/Raulcudris/ArchitectureMicroservicesJava.git
          search-paths: config-data
  application:
    name: Config-Services
