server:
  port: 8082

spring:
  application:
    name: ShoppingCartApplication
  datasource:
     url: jdbc:mysql://localhost:3306/shoppingstore
     username: admin
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
  mysql:
    url: jdbc:mysql://localhost:3306/shoppingstore
    username: admin
    password: root

